name: Test

on:
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    name: 'Lint Yaml'
    uses: PHPCSStandards/.github/.github/workflows/reusable-yamllint.yml@main
    with:
      strict: true

  markdownlint:
    name: 'Lint Markdown'
    uses: PHPCSStandards/.github/.github/workflows/reusable-markdownlint.yml@main

  remark:
    name: 'QA Markdown'
    uses: PHPCSStandards/.github/.github/workflows/reusable-remark.yml@main

  test:
    needs: yamllint

    name: "${{ matrix.name }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          ####################################################
          # Basic action input handling.
          ####################################################

          # Test input handling: missing required input.
          - name: "Test required input missing"
            expected: "fail"

          ####################################################
          # Basic well-formedness tests.
          ####################################################

          # Test basic well-formedness validation.
          - name: "Test no XSD, valid XML"
            pattern: tests/fixtures/valid-basic.xml
            expected: success

          - name: "Test no XSD, invalid XML"
            pattern: tests/fixtures/invalid-basic.xml
            expected: fail

          # Test that glob patterns are handled correctly.
          - name: "Test no XSD, glob, valid XML files"
            pattern: ./tests/fixtures/all-valid-basic/*.xml
            expected: success

          - name: "Test no XSD, glob, invalid XML files"
            pattern: ./tests/*/some-valid-basic/*.xml
            expected: fail

          ####################################################
          # Validate against a local XSD file.
          ####################################################

          # Test input handling: optional XSD file.
          - name: "Test XSD file wrong file extension"
            pattern: tests/fixtures/valid-local.xml
            xsd-file: tests/fixtures/xsd-files/wrong-extension.notxsd
            expected: "fail"

          - name: "Test XSD file doesn't exist"
            pattern: tests/fixtures/valid-local.xml
            xsd-file: tests/fixtures/xsd-files/file-does-not-exist.xsd
            expected: "fail"

          - name: "Test XSD file empty"
            pattern: tests/fixtures/valid-local.xml
            xsd-file: tests/fixtures/xsd-files/file-is-empty.xsd
            expected: "fail"

          # Test validating against a local XSD schema.
          - name: "Test XSD file, valid XML + schema"
            pattern: tests/fixtures/valid-local.xml
            xsd-file: tests/fixtures/xsd-files/valid-local.xsd
            expected: "success"

          - name: "Test XSD file, invalid XML"
            pattern: tests/fixtures/invalid-basic.xml
            xsd-file: tests/fixtures/xsd-files/valid-local.xsd
            expected: "fail"

          - name: "Test XSD file, valid XML, not schema"
            pattern: tests/fixtures/invalid-local.xml
            xsd-file: tests/fixtures/xsd-files/valid-local.xsd
            expected: "fail"

          # Test that glob patterns are handled correctly in combination with a local XSD schema.
          - name: "Test XSD file, glob, valid XML + schema"
            pattern: ./tests/fixtures/all-valid-local-xsd/*.xml
            xsd-file: tests/fixtures/xsd-files/valid-local.xsd
            expected: "success"

          - name: "Test XSD file, glob, valid XML, not schema"
            pattern: ./tests/fixtures/some-*-local-xsd/*.xml
            xsd-file: tests/fixtures/xsd-files/valid-local.xsd
            expected: "fail"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run the test
        id: xmllint-validate
        continue-on-error: true
        uses: ./
        with:
          pattern: ${{ matrix.pattern }}
          xsd-file: ${{ matrix.xsd-file }}

      - name: "Check the result of a successful test against expectation"
        if: ${{ steps.xmllint-validate.outcome == 'success' }}
        run: |
          if [ "${{ matrix.expected == 'fail' }}" == "true" ]; then
            exit 1
          fi

      - name: "Check the result of a failed test against expectation"
        if: ${{ steps.xmllint-validate.outcome != 'success' }}
        run: |
          if [ "${{ matrix.expected == 'success' }}" == "true" ]; then
            exit 1
          fi
